# Generated by Django 4.2.7 on 2025-09-08 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('linkedin_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HiringManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('invited', 'Invité'), ('started', 'Commencé'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='invited', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('access_token', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.IntegerField()),
                ('preparation_time', models.IntegerField(default=30)),
                ('response_time_limit', models.IntegerField(default=120)),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VideoCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('preparation_time', models.IntegerField(default=30)),
                ('response_time_limit', models.IntegerField(default=120)),
                ('max_questions', models.IntegerField(default=5)),
                ('allow_retry', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('hiring_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='interviews.hiringmanager')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_video_size', models.IntegerField(default=500)),
                ('enable_audio', models.BooleanField(default=True)),
                ('enable_video', models.BooleanField(default=True)),
                ('resolution', models.CharField(default='1280x720', max_length=10)),
                ('allowed_formats', models.JSONField(default=list)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_settings', to='interviews.videocampaign')),
            ],
        ),
        migrations.CreateModel(
            name='VideoResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='video_responses/')),
                ('video_url', models.URLField(blank=True)),
                ('duration', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('preparation_time_used', models.IntegerField(default=0)),
                ('response_time_used', models.IntegerField(default=0)),
                ('upload_status', models.CharField(choices=[('uploading', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec')], default='uploading', max_length=20)),
                ('file_size', models.IntegerField(default=0)),
                ('format', models.CharField(max_length=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interviews.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interviews.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('hiring_manager', 'Recruteur'), ('candidate', 'Candidat'), ('admin', 'Administrateur')], default='candidate', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='interviews.interviewsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.videocampaign'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='interviews.videocampaign'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='interviews.candidate'),
        ),
        migrations.AddField(
            model_name='hiringmanager',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_manager', to='interviews.userprofile'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skill', models.IntegerField(blank=True, choices=[(1, '1★'), (2, '2★'), (3, '3★'), (4, '4★'), (5, '5★')], null=True)),
                ('communication', models.IntegerField(blank=True, choices=[(1, '1★'), (2, '2★'), (3, '3★'), (4, '4★'), (5, '5★')], null=True)),
                ('motivation', models.IntegerField(blank=True, choices=[(1, '1★'), (2, '2★'), (3, '3★'), (4, '4★'), (5, '5★')], null=True)),
                ('cultural_fit', models.IntegerField(blank=True, choices=[(1, '1★'), (2, '2★'), (3, '3★'), (4, '4★'), (5, '5★')], null=True)),
                ('notes', models.TextField(blank=True)),
                ('recommended', models.BooleanField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('hiring_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.hiringmanager')),
                ('video_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='interviews.videoresponse')),
            ],
            options={
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_campaigns', models.IntegerField(default=0)),
                ('active_campaigns', models.IntegerField(default=0)),
                ('total_candidates', models.IntegerField(default=0)),
                ('completed_interviews', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hiring_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interviews.hiringmanager')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='interviews.userprofile'),
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech_confidence', models.FloatField(blank=True, null=True)),
                ('speech_rate', models.FloatField(blank=True, null=True)),
                ('filler_words_count', models.IntegerField(default=0)),
                ('eye_contact_score', models.FloatField(blank=True, null=True)),
                ('posture_score', models.FloatField(blank=True, null=True)),
                ('gesture_score', models.FloatField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_version', models.CharField(default='1.0', max_length=20)),
                ('video_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='interviews.videoresponse')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False)),
                ('can_view_responses', models.BooleanField(default=True)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.videocampaign')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_campaigns', to='interviews.hiringmanager')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_campaigns', to='interviews.hiringmanager')),
            ],
            options={
                'unique_together': {('campaign', 'shared_with')},
            },
        ),
    ]
