# Generated by Django 4.2.7 on 2025-09-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
